cache: bundler
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-2.2.3
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 1.9.2
    - rvm: 1.8.7
env:
  - CXX=g++-4.8
  - CXX=clang++
notifications:
  recipients:
    - cowboyd@thefrontside.net
before_install:
  - gem update --system 2.1.11
script:
  - CXX=g++-4.8 bundle exec rake compile
  - bundle exec rspec spec/c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
